Vagrant.configure("2") do |config|
  # Box base
  config.vm.box = "ubuntu/focal64"

  # VM1
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.56.10"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-vm1"
      vb.memory = 512
    end
  end

  # VM2
  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.56.11"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-vm2"
      vb.memory = 512
    end
  end
end
